version: '3'

services:
  ##########################################
  # Overrides for oada-core services:
  ##########################################

  # Add ourselves to yarn to do yarn install
  yarn:
    volumes:
      - ./services-available/target-helper:/code/target-helper

  # Add ourselves to admin container:
  admin:
    volumes:
      - ./services-available/target-helper:/code/target-helper

  ###############################################
  # This service's definition:
  ###############################################
  target-helper:
    build:
      context: ./services-available/target-helper
    container_name: target-helper
    restart: always
    networks:
      - http_net
      - startup_net
    volumes:
      - ./services-available/target-helper:/code/target-helper
      - ./oada-core/libs:/code/libs
      - ./oada-srvc-docker-config.js:/oada-srvc-docker-config.js
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG=${DEBUG:-"target-helper:info,*warn*,*error*"}
      - domain
      - token
