services:
  target-helper:
    build:
      context: ./services/target-helper
    restart: unless-stopped
    volumes:
      - ./services/target-helper:/code/target-helper
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG=${DEBUG:-"target-helper:info,*warn*,*error*"}
      - token=${TARGET_HELPER_TOKEN}
      # Connect to host if DOMAIN not set?
      # You should really not rely on this though. Set DOMAIN.
      - domain=${DOMAIN:-host.docker.internal}
